### ISSUE TITLE
mybinder ipywidgets didn't work as environment.yaml

### ISSUE THREAD

**Issue by pelson** [SciTools/cube_browser#100]
Just done some digging, and it looks as though, unless binder install ipywidgets into the notebook environment (they don't currently), it is not possible to install ipywidgets using the environment.yaml form. This is because it is necessary to install ipywidgets before `jupyter notebook` is run, and that isn't done.

In short - the only way to get ipywidgets installed correctly on mybinder at the moment is to use a dockerfile. PR incoming.

For reference, the message was:

```
Widget Javascript not detected.  It may not be installed properly. Did you enable the widgetsnbextension? If not, then run "jupyter nbextension enable --py --sys-prefix widgetsnbextension"
```

**Comment by pelson** [comment]
We added a Dockerfile instead (#101). We should report this to the mybinder codebase, but closing as it isn't a cube_browser issue.

**Comment by aflaxman** [comment]
I'm running into this same issue on [a repo](https://github.com/aflaxman/iths-communicating-results-visually-2), do you happen to know if there is a simpler soln now? /cc @freeman-lab @andrewosh

**Comment by aflaxman** [comment]
I followed your solution and I'm all sorted out now.  https://github.com/aflaxman/iths-communicating-results-visually-2/blob/master/Dockerfile  Thanks!
