### ISSUE TITLE
Overplotting

### ISSUE THREAD

**Issue by dkillick** [SciTools/cube_browser#125]
Plot multiple phenomena on a single set of axes and make use of Cube Browser animations and goodness.

**Comment by bjlittle** [comment]
@dkillick Can you be more specific? We can already overlay plots onto a single axes ... or is there more to this?

**Comment by dkillick** [comment]
Oooh, can we? If we can then this isn't needed! I just didn't know if we could or not...

**Comment by bjlittle** [comment]
Yup, works as far as I know. Confirm with @marqh but I think that we can close this issue
