### ISSUE TITLE
Cube explorer plot menu - no. of pages determined by no. of subplots 

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/cube_browser#126]
The cube explorer always has two pages under the "Plots" menu. This has confused some users and has lead to them misunderstanding what a Page is.

If each page refers to a subplot, when only 1 subplot is selected, there should be 1 page, when 2 subplots are selected, there should be two pages.

**Comment by marqh** [comment]
complete

**Comment by lbdreyer** [comment]
For reference, it appears that this was dealt with in PR #131.
