### ISSUE TITLE
plot call kwargs format

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cube_browser#24]
How do we ask the user to provide input values for the plot calls?  That is, specifically, the __call__ function inside the plotting class (e.g. Contourf), which can be called either by the user to produce a static plot or repeatedly by the Browser to produce a new plot for every slider movement.

Currently this is:
```python
def __call__(self, **kwargs)
```
but this may become confusing for anonymous dimensions, specifically for the case in which the user wants a static plot, so do we replace **kwargs with a list of tuples, or a dictionary, or something else?

(My preference is a dictionary).

**Comment by bjlittle** [comment]
@corinnebosley We now have the concept of aliases, which means that a user can provided a name for an anonymous dimension. This also helps the browser to align/equate multiple anonymous dimensions across different plot cubes, and give a meaningful name to a slider.

This also means that the name is also used in the `__call__`.
