### ISSUE TITLE
refactor plot classes

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cube_browser#26]
There is a large amount of shared processing in the plot classes (especially for Contour and Contourf), so they need to be refactored so that repetition and processing is minimised.

**Comment by corinnebosley** [comment]
When you want to make a Contourf plot, you would say:

```python
plot1 = Contourf(cube, coords=('grid_longitude', 'grid_latitude'))
```
However, when you make a Plot plot, you really only need to choose one coordinate (this statement is a little tentative and open to debate), so we talked about saying:

```python
plot1 = Plot(cube, coord=('grid_longitude'))
```
The latter syntax is more intuitive, but if we keep the keyword as 'coords' then we can move functions 'coord_dims()' and 'slider_coords' (and currently 'new_axes()...' into a separate class(?) which can be shared with all plot types.  But this does mean saying:

```python
plot1 = Plot(cube, coords=('grid_longitude'))
```
How reasonable do we think that is?

**Comment by bjlittle** [comment]
@corinnebosley For `iplt.plot` there are six different call signatures that are a mixture of coordinates and/or cubes, where the cube must be 1d. 

I'd suggest the following approach to handle both `plot` and `scatter` ... in the examles below consider `cube` to be `(latitude: N, longitude: M)` ...

```python
# plot a 1d cube against its dimension coordinate
iplt.plot(cube)

# Defaults to the last cube dimension for the plot axis or nominate the coordinate ...
Plot(cube, coord='longitude')   # so this slides over 'latitude'
```
```python
# plot a 1d coordinate
iplt.plot(coord)

# This case is invariant, the coord provided must be 1d. 
# Supporting n-dim coords is another matter.
Plot(coord)  # invariant, so no sliding here.
```
```python
# plot a 1d cube against a given 1d coordinate, with the cube
# values on the y-axis and the coordinate on the x-axis
plot(coord, cube)

# Defaults to the last cube dimension for the plot axis or nominate the coordinate ...
Plot(coord, cube, coord='latitude')  # so this slides over 'longitude'
```
```python
# plot a 1d cube against a given 1d coordinate, with the cube
# values on the x-axis and the coordinate on the y-axis
plot(cube, coord)

# Defaults to the last cube dimension for the plot axis or nominate the coordinate ...
Plot(cube, coord, coord='latitude')  # so this slides over 'longitude'
```
```python
# plot two 1d coordinates against one-another
plot(coord1, coord2)

# This case is also invariant. No n-dim coord support (yet)
Plot(coord1, coord2)
```
```python
# plot two 1d cubes against one-another
plot(cube1, cube2)

# The interesting case ...
# Again, defaults to the last cube dimension, or nominate
Plot(cube1, cube2, xcoord='longitude', ycoord='latitude')
```

The `coord`, `xcoord` and `ycoord` are not passed down to the underlying `iplt.plot`, they are the exception and are there to control which dimensions are slid over.

Something, along those lines ...
