### ISSUE TITLE
interactive plot closed by autosave

### ISSUE THREAD

**Issue by marqh** [SciTools/cube_browser#31]

**Comment by corinnebosley** [comment]
Can we disable autosave as a temporary workaround?

**Comment by bjlittle** [comment]
@corinnebosley If it helps with progress making a local change to your notebook session whilst developing so that you're not hitting this issue, then I'd agree to that in the short-term.

**Comment by corinnebosley** [comment]
Suppose I should really work out how (and if) I can do that then...

**Comment by marqh** [comment]
see #42 which disables this by default for cube_browser notebooks
