### ISSUE TITLE
release docs

### ISSUE THREAD

**Issue by marqh** [SciTools/cube_browser#68]
documentation ready for release

**Comment by corinnebosley** [comment]
**Notes on Binder:**

So far this looks quite exciting, and I am impressed.  This is how it works:
- We have a repo with notebooks in which we want anybody to be able to use no matter what their environment
- We make a file in the repo called index.ipynb and a file containing the environment specs for the notebooks (this can be a yml file describing a conda env or a txt file describing pip installs, or a docker file)
- We press a big red button (it's not really red, but it should be) on the binder website and it makes a badge in the repo
- When you click the badge, the environment is activated and the index notebook is opened
- You can copy and paste the badge URL from github to share the link.

I am a little unsure of structure at the moment, but I am going to play around with it to find out.

**Comment by corinnebosley** [comment]
I have been having a look at the example repos on the Binder website, and so far the binder badge on every single one has failed to load.  This is not so good... I can only keep trying.

**Comment by corinnebosley** [comment]
**Summary of Binder:**

This seems to have its advantages and disadvantages.  

Advantages:
    -  Really useful for opening an environment anywhere on any machine to run a notebook
    -  You can extend the badge URL to run any notebook in the repo tree from a link
    -  It's exciting
Disadvantages:
    -  Has a lot of bugs and issues because it's very new
    -  It doesn't track changes in the repo, so you have to manually rebuild the binder when necessary
    -  It can't track branches

I am still trying to find a way to make the binder track changes in the repo, but it looks at the moment like it will have to be rebuilt manually upon every release, which is not ideal.

**Comment by corinnebosley** [comment]
**Notes on Azure:**

Don't like it.
