### ISSUE TITLE
Upgrade ipywidgets in conda cb recipe

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cube_browser#83]
Current version is 4.1.1, but this does not have SelectionSlider, so needs to be upgraded to 5.1.3

**Comment by corinnebosley** [comment]
Current version is 4.1.1, but this does not have SelectionSlider, so needs to be upgraded to 5.1.3

**Comment by bjlittle** [comment]
Closed by https://github.com/SciTools/conda-recipes-scitools/pull/157
