### ISSUE TITLE
Add sphinx_rtd_theme to conda cb recipe

### ISSUE THREAD

**Issue by corinnebosley** [SciTools/cube_browser#84]
This needs to be added in order for the docs makefile to work.

Also need to resolve Sphinx python version issue after addition of this module.

**Comment by corinnebosley** [comment]
Regarding Sphinx python version issue:

In working environment, sphinx version is 1.4.1

In new environment, sphinx version is 1.2.1

In the latter version, sphinx is using my local python rather than the environment version, which means that it can't find the modules that it needs in order to run the makefile.

**Comment by bjlittle** [comment]
Won't add this to the recipe.

It's acceptable for the user can install sphinx in their conda environment themselves.
